/*
DELETE FROM P2P_HISTORICO_NEGOCIO;
DELETE FROM P2P_OCORRENCIA;
DELETE FROM P2P_ESPOLIO;
DELETE FROM P2P_ANUNCIO_ITEM;
DELETE FROM P2P_ANUNCIO;
DELETE FROM P2P_ITEM;
DELETE FROM P2P_PERSONAGEM;
DELETE FROM P2P_MOVIMENTACAO;
DELETE FROM P2P_CATEGORIA;
DELETE FROM P2P_USUARIO;
*/


INSERT INTO P2P_USUARIO(
    NOME, USERNAME, EMAIL, SENHA) VALUES
    (
    'OTAVIO', 'FRASSAO', 'otavio-frassao@hotmail.com', 'OTAVIO123'
    );
    
INSERT INTO P2P_USUARIO(
    NOME, USERNAME, EMAIL, SENHA) VALUES
    (
    'MARIA LUISA', 'ML_LOPES', 'ml_lopes@gmail.com', 'MARIALUISA123'
    );
INSERT INTO P2P_USUARIO(
    NOME, USERNAME, EMAIL, SENHA) VALUES (
    'CARLOS SILVA', 'CSILVA', 'carlos.silva@email.com', 'CARLOS123'
    );
SELECT * FROM P2P_USUARIO;

INSERT INTO P2P_CATEGORIA(
    COD_CATEGORIA, NOME, TIPO) VALUES (
        'EP', 'ESPADA', 1
    ); --PRODUTO
INSERT INTO P2P_CATEGORIA(
    COD_CATEGORIA, NOME, TIPO) VALUES (
        'FE', 'FERRO', 0
    ); --MATERIA PRIMA
INSERT INTO P2P_CATEGORIA(
    COD_CATEGORIA, NOME, TIPO) VALUES (
        'BR', 'BRONZE', 0
    ); --MATERIA PRIMA
INSERT INTO P2P_CATEGORIA(
    COD_CATEGORIA, NOME, TIPO) VALUES (
        'CJ', 'CAJADO', 1
    ); --PRODUTO
    
SELECT * FROM P2P_CATEGORIA;

INSERT INTO P2P_PERSONAGEM(
    TIPO, NICKNAME, COD_NPC, NIVEL) VALUES (
        1, 'MAGO','MAG', NULL
    ); --NPC
INSERT INTO P2P_PERSONAGEM(
    TIPO, NICKNAME, COD_NPC, NIVEL) VALUES (
        1, 'FERREIRO','FER', NULL
    ); --NPC
INSERT INTO P2P_PERSONAGEM(
    ID_USUARIO, TIPO, NICKNAME, NIVEL) VALUES (
        1, 0, 'FRASSAO6967', 1
    ); --USUARIO
INSERT INTO P2P_PERSONAGEM(
    ID_USUARIO, TIPO, NICKNAME, NIVEL) VALUES (
        2, 0, 'MARIA_MAGE', 5
        ); --USUARIO
INSERT INTO P2P_PERSONAGEM(
    ID_USUARIO, TIPO, NICKNAME, NIVEL) VALUES (
        5, 0, 'CSILVA_WARRIOR', 3
        ); --USUARIO
SELECT * FROM P2P_PERSONAGEM;

INSERT INTO P2P_ITEM(
    ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) VALUES (
        1, 'EPB', 'ESPADA DE BRONZE', 0, 'ESPADA FORJADA NO BRONZE DAS MONTANHAS DE NILGAR'
    );
INSERT INTO P2P_ITEM(
    ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) VALUES (
        1, 'EPL', 'ESPADA LENDARIA', 3, 'ESPADA PERDIDA DO CAVALEIRO DE OURO DE OLFST'
    );
INSERT INTO P2P_ITEM(
    ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) VALUES (
        2, 'FEL', 'FERRO DE LITIUM', 1, 'FERRO PARA FORJAR ITENS DE LITIUM'
    );
INSERT INTO P2P_ITEM(
    ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) VALUES (
        3, 'MIB', 'MINERIO DE BRONZE', 0, 'MINEIRO DE BRONZE PARA FORJAR ITENS'
    );
INSERT INTO P2P_ITEM(
    ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) VALUES (
        4, 'CJM', 'CAJADO DE MAGO', 1, 'CAJADO DROPADO DE UM MAGO COMUM'
    );

SELECT * FROM P2P_ITEM;

INSERT INTO P2P_ESPOLIO(
    ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT, QNT_MIN, QNT_MAX) VALUES (
        1, 1, 9, 40, NULL, 1, 4
    );
INSERT INTO P2P_ESPOLIO(
    ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT, QNT_MIN, QNT_MAX) VALUES (
        2, 1, 4, 80, NULL, 1, 15
    );
    SELECT * FROM P2P_PERSONAGEM;
    SELECT * FROM P2P_ITEM;
    SELECT * FROM P2P_ESPOLIO;
