/*
DELETE FROM P2P_HISTORICO_NEGOCIO;
DELETE FROM P2P_OCORRENCIA;
DELETE FROM P2P_ESPOLIO;
DELETE FROM P2P_ANUNCIO_ITEM;
DELETE FROM P2P_ANUNCIO;
DELETE FROM P2P_ITEM;
DELETE FROM P2P_PERSONAGEM;
DELETE FROM P2P_MOVIMENTACAO;
DELETE FROM P2P_CATEGORIA;
DELETE FROM P2P_USUARIO;
*/

-- usuario
INSERT INTO P2P_USUARIO (NOME, USERNAME, EMAIL, SENHA) 
    VALUES ('Maria','maria123','maria@gmail.com','12345678');
INSERT INTO P2P_USUARIO (NOME, USERNAME, EMAIL, SENHA) 
    VALUES ('João','joao123','joao@gmail.com','12345678');

-- categoria
   -- produto
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('WPN','Armas',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('ARM','Armadura',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('ACC','Acessórios',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('POT','Poções',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('ALI','Alimentos',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('FER','Ferramentas',1);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('MON','Monetário',1);
    
    -- matéria-prima
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('MIN','Minérios',0);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('PLA','Plantas',0);
INSERT INTO P2P_CATEGORIA (COD_CATEGORIA, NOME, TIPO) 
    VALUES ('TEC','Tecidos',0);
    
-- personagem
    -- jogador
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL) 
    VALUES (1,0,'marinr',10);
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL) 
    VALUES (2,0,'sonejojo' ,10);
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL) 
    VALUES (1,0,'lexidrani', 0);
    
    -- npc
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME, COD_NPC) 
    VALUES (1,'Esqueleto', 'ESQ');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME, COD_NPC) 
    VALUES (1,'Mago', 'MAG');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME, COD_NPC) 
    VALUES (1,'Dragão', 'DRA');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME, COD_NPC) 
    VALUES (1,'Alquimista', 'ALQ');

-- item
    -- gold
INSERT INTO P2P_ITEM (ID_ITEM, ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) 
    VALUES (1, 10,'GLD', 'Gold',0,'Dinheiro');
    -- outros
INSERT INTO P2P_ITEM (ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) 
    VALUES (4,'CUR', 'Poção de Cura',0,'+4 HP');
INSERT INTO P2P_ITEM (ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) 
    VALUES (1,'ESP', 'Espada de Vidro',1,'+2 DMG, -1 DUR');
INSERT INTO P2P_ITEM (ID_CATEGORIA, COD_ITEM, NOME, RARIDADE, DESCRICAO) 
    VALUES (3,'MAR', 'Martelo',0,'Usado para criar escudos');
    
-- espólio
    -- npc
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT_MIN, QNT_MAX) 
    VALUES (5,1, 1,90, 100,200);
    INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT_MIN, QNT_MAX) 
    VALUES (5,1, 4,40, 1, NULL);
    
    -- jogador
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (1,0,1,250);
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (1,0,2,10);
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (1,0,3,2);
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (2,0, 1,100);
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (2,0, 3,12);
INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT) 
    VALUES (2,0, 2,3);