/*
DELETE FROM P2P_HISTORICO_NEGOCIO;
DELETE FROM P2P_ANUNCIO_ITEM;
DELETE FROM P2P_ANUNCIO;
DELETE FROM P2P_OCORRENCIA;
DELETE FROM P2P_ESPOLIO;
DELETE FROM P2P_PERSONAGEM;
DELETE FROM P2P_USUARIO;
DELETE FROM P2P_ITEM;
DELETE FROM P2P_CATEGORIA;
DELETE FROM P2P_TABELA_ALVO;
DELETE FROM P2P_MOVIMENTACAO;
-----------------------------------
SELECT * FROM P2P_HISTORICO_NEGOCIO;
SELECT * FROM P2P_ANUNCIO_ITEM;
SELECT * FROM P2P_ANUNCIO;
SELECT * FROM P2P_OCORRENCIA;
SELECT * FROM P2P_ESPOLIO;
SELECT * FROM P2P_PERSONAGEM;
SELECT * FROM P2P_USUARIO;
SELECT * FROM P2P_ITEM;
SELECT * FROM P2P_CATEGORIA;
SELECT * FROM P2P_TABELA_ALVO;
SELECT * FROM P2P_MOVIMENTACAO;
*/

-------- TABELA_ALVO ----------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial do catálogo de tabelas');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (9, 'P2P_TABELA_ALVO', 'ID_TABELA');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 9, 'Cadastro de P2P_TABELA_ALVO no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (1, 'P2P_USUARIO', 'ID_USUARIO');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 1, 'Cadastro de P2P_USUARIO no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (2, 'P2P_CATEGORIA', 'ID_CATEGORIA');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 2, 'Cadastro de P2P_CATEGORIA no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (3, 'P2P_PERSONAGEM', 'ID_PERSONAGEM');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 3, 'Cadastro de P2P_PERSONAGEM no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (4, 'P2P_ITEM', 'ID_ITEM');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 4, 'Cadastro de P2P_ITEM no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (5, 'P2P_ANUNCIO', 'ID_ANUNCIO');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 5, 'Cadastro de P2P_ANUNCIO no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (6, 'P2P_ANUNCIO_ITEM', 'ID_ANUNCIO_ITEM');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 6, 'Cadastro de P2P_ANUNCIO_ITEM no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (7, 'P2P_ESPOLIO', 'ID_ESPOLIO');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 7, 'Cadastro de P2P_ESPOLIO no catálogo');

INSERT INTO P2P_TABELA_ALVO (ID_TABELA, NOME, PK)
    VALUES (8, 'P2P_HISTORICO_NEGOCIO', 'ID_HISTORICO');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (1, 9, 8, 'Cadastro de P2P_HISTORICO_NEGOCIO no catálogo');

-------- CATEGORIA ------------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de categorias');

INSERT INTO P2P_CATEGORIA (ID_CATEGORIA, NOME, TIPO)
    VALUES (1, 'Monetário', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 1, 'Cadastro da categoria Monetário');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Armas', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 2, 'Cadastro da categoria Armas');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Armadura', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 3, 'Cadastro da categoria Armadura');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Poções', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 4, 'Cadastro da categoria Poções');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Acessórios', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 5, 'Cadastro da categoria Acessórios');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Alimentos', 1);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 6, 'Cadastro da categoria Alimentos');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Minérios', 0);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 7, 'Cadastro da categoria Minérios');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Plantas', 0);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 8, 'Cadastro da categoria Plantas');

INSERT INTO P2P_CATEGORIA (NOME, TIPO)
    VALUES ('Tecidos', 0);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (2, 2, 9, 'Cadastro da categoria Tecidos');

-------- ITEM -----------------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de itens');

INSERT INTO P2P_ITEM (ID_ITEM, ID_CATEGORIA, RARIDADE, NOME, DESCRICAO)
    VALUES (1, 1, 1, 'Ouro', 'Moeda de Ouro');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (3, 4, 1, 'Cadastro do item Ouro');

INSERT INTO P2P_ITEM (ID_CATEGORIA, RARIDADE, NOME, DESCRICAO)
    VALUES (4, 1, 'Poção de Cura', '+4 HP');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (3, 4, 2, 'Cadastro do item Poção de Cura');

INSERT INTO P2P_ITEM (ID_CATEGORIA, RARIDADE, NOME, DESCRICAO)
    VALUES (2, 2, 'Espada de Vidro', '+2 DMG, -1 DUR');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (3, 4, 3, 'Cadastro do item Espada de Vidro');

INSERT INTO P2P_ITEM (ID_CATEGORIA, RARIDADE, NOME, DESCRICAO)
    VALUES (6, 2, 'Torta de Maça', '+1 MAX-HP 2min');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (3, 4, 4, 'Cadastro do item Torta de Maça');

-------- USUARIO --------------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Usuário');
INSERT INTO P2P_USUARIO (NOME, USERNAME, EMAIL, SENHA)
    VALUES ('Maria', 'maria123', 'maria@gmail.com', '12345678');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (4, 1, 1, 'Cadastro do usuário Maria');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Usuário');
INSERT INTO P2P_USUARIO (NOME, USERNAME, EMAIL, SENHA)
    VALUES ('João', 'joao123', 'joao@gmail.com', '12345678');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (5, 1, 2, 'Cadastro do usuário João');


-------- PERSONAGEM -----------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL)
    VALUES (1, 0, 'marinr', 10);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (6, 3, 1, 'Cadastro do jogador marinr');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL)
    VALUES (2, 0, 'sonejojo', 10);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (7, 3, 2, 'Cadastro do jogador sonejojo');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (ID_USUARIO, TIPO, NICKNAME, NIVEL)
    VALUES (1, 0, 'lexidrani', 0);
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (8, 3, 3, 'Cadastro do jogador lexidrani');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME)
    VALUES (1, 'Esqueleto');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (9, 3, 4, 'Cadastro do NPC Esqueleto');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME)
    VALUES (1, 'Mago');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (10, 3, 5, 'Cadastro do NPC Mago');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME)
    VALUES (1, 'Dragão');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (11, 3, 6, 'Cadastro do NPC Dragão');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Cadastro de Personagem');
INSERT INTO P2P_PERSONAGEM (TIPO, NICKNAME)
    VALUES (1, 'Alquimista');
INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (12, 3, 7, 'Cadastro do NPC Alquimista');

-------- ESPOLIO --------------------------------------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de um Espólio NPC');
INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT_MIN, QNT_MAX)
    VALUES (4, 1, 1, 90, 100, 200);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (13, 7, 1, 'Cadastro do espólio de Ouro do Esqueleto');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, PROBABILIDADE, QNT_MIN, QNT_MAX)
    VALUES (4, 1, 3, 40, 1, NULL);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (13, 7, 2, 'Cadastro do espólio de Espada de Vidro do Esqueleto');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de um Espólio Jogador');
INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (1, 0, 1, 250);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (14, 7, 3, 'Cadastro do espólio de Ouro de marinr');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (1, 0, 2, 10);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (14, 7, 4, 'Cadastro do espólio de Poção de Cura de marinr');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (1, 0, 4, 5);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (14, 7, 5, 'Cadastro do espólio de Torta de Maça de marinr');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de um Espólio Jogador');
INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (2, 0, 1, 100);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (15, 7, 6, 'Cadastro do espólio de Ouro de sonejojo');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (2, 0, 3, 12);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (15, 7, 7, 'Cadastro do espólio de Espada de Vidro de sonejojo');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (2, 0, 2, 3);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (15, 7, 8, 'Cadastro do espólio de Poção de Cura de sonejojo');

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Carga inicial de um Espólio Jogador');
INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (3, 0, 1, 0);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (16, 7, 9, 'Cadastro do espólio de Ouro de lexidrani');

INSERT INTO P2P_ESPOLIO
    (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (3, 0, 4, 25);
INSERT INTO P2P_OCORRENCIA
    (ID_MOVIMENTACAO, ID_TABELA, ID_REGISTRO, DESCRICAO)
    VALUES (16, 7, 10, 'Cadastro do espólio de Torta de Maça de lexidrani');

-------- FLUXO DE UMA LUTA COM ITEM NO ESPÓLIO --------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Luta: Esqueleto -> Lexidrani, 50 Ouro');

UPDATE P2P_ESPOLIO
    SET QNT = QNT + 50
    WHERE ID_ESPOLIO = 9;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_ORIGEM, ID_DESTINO, ID_ESPOLIO, QNT, DESCRICAO)
    VALUES (17, 4, 3, 1, 50,'Transferência de 50 Ouro do Esqueleto para Lexidrani');

-------- FLUXO DE UMA LUTA SEM ITEM NO ESPÓLIO --------------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Luta: Esqueleto -> Lexidrani, 1 Espada de Vidro');

INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (3, 0, 3, 1);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, ID_ORIGEM, ID_DESTINO, ID_ESPOLIO, QNT, DESCRICAO)
    VALUES (18, 4, 3, 2, 1, 'Transferência de 1 Espada de Vidro do Esqueleto para Lexidrani');
    
-------- FLUXO DE COMPRA E VENDA INCIADO COMO VENDA ---------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Criação de anúncio');

INSERT INTO P2P_ANUNCIO (ID_ANUNCIANTE, ID_INTERESSADO, TIPO, TITULO, DESCRICAO)
    VALUES (1, NULL, 1, 'Vendo 1 Poção de Cura por 10g', 'Não aceito troca');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (19, 'Criação do anúncio de venda', 1);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (1, 2, 1, 1);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (19, 'Inclusão de 1 Poção de Cura como item solicitado', 1);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (1, 1, 0, 10);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (19, 'Inclusão de 10 Ouro como item ofertado', 1);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Negociação de anúncio de venda');

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (1, 2, 0, 'Preciso de 3 Poções de Cura. 25 Ouro?');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (20, 'sonejojo enviou uma proposta de negociação', 2);

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (1, 1, 1, 'OK');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (20, 'marinr respondeu à proposta de negociação', 1);

UPDATE P2P_ANUNCIO_ITEM
    SET QNT = 3
    WHERE ID_ANUNCIO_ITEM = 1;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (20, 'Alteração da quantidade de Poções de Cura de 1 para 3', 1);

UPDATE P2P_ANUNCIO_ITEM
    SET QNT = 25
    WHERE ID_ANUNCIO_ITEM = 2;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (20, 'Alteração da quantidade de Ouro de 10 para 25', 1);

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (1, 2, 0, 'Perfeito!');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (20, 'sonejojo aceitou a negociação', 2);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Venda de item através de anúncio');

UPDATE P2P_ANUNCIO
    SET ID_INTERESSADO = 2,
        STATUS = 2,
        FECHADO_EM = SYSDATE
    WHERE ID_ANUNCIO = 1;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (21, 'Fechamento do anúncio de venda', 1);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 25
    WHERE ID_ESPOLIO = 6;

UPDATE P2P_ESPOLIO
    SET QNT = QNT + 25
    WHERE ID_ESPOLIO = 3;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ESPOLIO, QNT)
    VALUES (21, 'sonejojo -> marinr, 25 Ouro', 2, 1, 6, 25);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 3
    WHERE ID_ESPOLIO = 4;

UPDATE P2P_ESPOLIO
    SET QNT = QNT + 3
    WHERE ID_ESPOLIO = 8;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ANUNCIO_ITEM, QNT)
    VALUES (21, 'marinr -> sonejojo, 3 Poções de Cura', 1, 2, 1, 3);

-------- FLUXO DE COMPRA E VENDA INCIADO COMO COMPRA --------------------------
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Criação de anúncio');

INSERT INTO P2P_ANUNCIO (ID_ANUNCIANTE, ID_INTERESSADO, TIPO, TITULO, DESCRICAO)
    VALUES (2, NULL, 2, 'Compro 3 Tortas de Maça por 1 Espada de Vidro', 'Aceito troca');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (22, 'Criação do anúncio de compra', 2);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (2, 4, 1, 3);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (22, 'Inclusão de 3 Tortas de Maça como item solicitado', 2);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (2, 3, 0, 1);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (22, 'Inclusão de 1 Espada de Vidro como item ofertado', 2);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Negociação de anúncio de compra');

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (2, 1, 0, 'Tenho 3 Tortas de Maça. Fechado por 1 Espada de Vidro.');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (23, 'marinr respondeu ao anúncio de compra', 1);

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (2, 2, 1, 'Fechado.');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (23, 'sonejojo aceitou a negociação', 2);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Compra de item através de anúncio');

UPDATE P2P_ANUNCIO
    SET ID_INTERESSADO = 1,
        STATUS = 2,
        FECHADO_EM = SYSDATE
    WHERE ID_ANUNCIO = 2;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (24, 'Fechamento do anúncio de compra', 2);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 1
    WHERE ID_ESPOLIO = 7;

INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (1, 0, 3, 1);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ESPOLIO, QNT)
    VALUES (24, 'sonejojo -> marinr, 1 Espada de Vidro', 2, 1, 7, 1);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 3
    WHERE ID_ESPOLIO = 5;

INSERT INTO P2P_ESPOLIO (ID_PERSONAGEM, TIPO, ID_ITEM, QNT)
    VALUES (2, 0, 4, 3);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ANUNCIO_ITEM, QNT)
    VALUES (24, 'marinr -> sonejojo, 3 Tortas de Maça', 1, 2, 3, 3);

-------- FLUXO DE LEILÃO ------------------------------------------------------

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Criação de anúncio');

INSERT INTO P2P_ANUNCIO (ID_ANUNCIANTE, ID_INTERESSADO, TIPO, TITULO, DESCRICAO, LANCE_DIRETO, MIN_LANCE)
    VALUES (3, NULL, 3, 'Leilão de 2 Tortas de Maça por Ouro', 'Maior lance vence', 50, 30);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (25, 'Criação do anúncio de leilão', 3);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (3, 4, 1, 2);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (25, 'Inclusão de 2 Tortas de Maça como item solicitado', 3);

INSERT INTO P2P_ANUNCIO_ITEM (ID_ANUNCIO, ID_ITEM, ACAO, QNT)
    VALUES (3, 1, 0, 30);

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (25, 'Inclusão de 30 Ouro como item ofertado', 3);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Negociação de anúncio de leilão');

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (3, 1, 0, 'Dou 40 Ouro pelas 2 Tortas de Maça.');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (26, 'marinr realizou um lance de 40 Ouro', 1);

UPDATE P2P_ANUNCIO_ITEM
    SET QNT = 40
    WHERE ID_ANUNCIO_ITEM = 6;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (26, 'Alteração da quantidade de Ouro de 30 para 40', 3);

INSERT INTO P2P_HISTORICO_NEGOCIO (ID_ANUNCIO, ID_PERSONAGEM, TIPO, MENSAGEM)
    VALUES (3, 3, 1, 'Lance aceito.');

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (26, 'lexidrani aceitou o lance de 40 Ouro', 3);

INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES ('Conclusão de leilão');

UPDATE P2P_ANUNCIO
    SET ID_INTERESSADO = 1,
        STATUS = 2,
        FECHADO_EM = SYSDATE
    WHERE ID_ANUNCIO = 3;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_DESTINO)
    VALUES (27, 'Fechamento do anúncio de leilão', 3);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 40
    WHERE ID_ESPOLIO = 3;

UPDATE P2P_ESPOLIO
    SET QNT = QNT + 40
    WHERE ID_ESPOLIO = 9;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ESPOLIO, QNT)
    VALUES (27, 'marinr -> lexidrani, 40 Ouro', 1, 3, 3, 40);

UPDATE P2P_ESPOLIO
    SET QNT = QNT - 2
    WHERE ID_ESPOLIO = 10;

UPDATE P2P_ESPOLIO
    SET QNT = QNT + 2
    WHERE ID_ESPOLIO = 5;

INSERT INTO P2P_OCORRENCIA (ID_MOVIMENTACAO, DESCRICAO, ID_ORIGEM, ID_DESTINO, ID_ANUNCIO_ITEM, QNT)
    VALUES (27, 'lexidrani -> marinr, 2 Tortas de Maça', 3, 1, 5, 2);