SET SERVEROUTPUT ON;
--ADD P2P_CATEGORIA FAZER UMA PROCEDURE

--CRIAR A MOVIMENTAÇÃO DA PROCEDURE
INSERT INTO P2P_MOVIMENTACAO (DESCRICAO)
    VALUES('Criação do procedure de P2P_CATEGORIA');


CREATE OR REPLACE PROCEDURE ADD_P2P_CATEGORIA(P_NOME IN P2P_CATEGORIA.NOME%TYPE, 
                                              P_TIPO IN P2P_CATEGORIA.TIPO%TYPE) IS
BEGIN
    
    INSERT INTO P2P_CATEGORIA (NOME, TIPO)
        VALUES (P_NOME, P_TIPO);
        
END ADD_P2P_CATEGORIA;
/
BEGIN
    ADD_P2P_CATEGORIA('AÇO INOXIDAVEL', 0);
    ADD_P2P_CATEGORIA('ESPADA DE COBRE', 1);
    ADD_P2P_CATEGORIA('ESCUDO DE MADEIRA', 1);
    ADD_P2P_CATEGORIA('MADEIRA', 0);
    ADD_P2P_CATEGORIA('CASCALHO', 0);
    ADD_P2P_CATEGORIA('COBRE', 0);
    ADD_P2P_CATEGORIA('SELA DE CAVALO', 1);
    ADD_P2P_CATEGORIA('DENTE DE DRAGAO', 0);
    ADD_P2P_CATEGORIA('POÇÃO DE VELOCIDADE', 1);
    ADD_P2P_CATEGORIA('POLVORA', 0);
END;
/   

SELECT *FROM P2P_CATEGORIA;

CREATE OR REPLACE PROCEDURE UPD_P2P_CATEGORIA(P_NOME IN P2P_CATEGORIA.NOME%TYPE,
                                              P_NOVO_TIPO IN P2P_CATEGORIA.TIPO%TYPE) IS
BEGIN
    UPDATE P2P_CATEGORIA
        SET TIPO = P_NOVO_TIPO
        WHERE NOME = P_NOME;
END UPD_P2P_CATEGORIA;
/

BEGIN
    UPD_P2P_CATEGORIA('AÇO INOXIDAVEL', 1);
    UPD_P2P_CATEGORIA('MADEIRA', 1);
    UPD_P2P_CATEGORIA('CASCALHO', 1);
    UPD_P2P_CATEGORIA('COBRE', 1);
    UPD_P2P_CATEGORIA('SELA DE CAVALO', 0);
    UPD_P2P_CATEGORIA('DENTE DE DRAGAO', 1);
END;
/

SELECT * FROM P2P_CATEGORIA;

CREATE OR REPLACE PROCEDURE DEL_P2P_CATEGORIA (P_TIPO IN P2P_CATEGORIA.TIPO%TYPE) IS
                                               
BEGIN
    DELETE FROM P2P_CATEGORIA
        WHERE TIPO = P_TIPO;
END DEL_P2P_CATEGORIA;
/

BEGIN
    DEL_P2P_CATEGORIA(0);
END;
/

SELECT * FROM P2P_CATEGORIA;

--CRIAR CRIAR PROCEDURE ADD, UPD, DEL DE ITEM

CREATE OR REPLACE PROCEDURE ADD_P2P_ITEM(P_ID_CATEGORIA IN P2P_ITEM.ID_CATEGORIA%TYPE,
                                         P_RARIDADE IN P2P_ITEM.RARIDADE%TYPE,
                                         P_NOME IN P2P_ITEM.NOME%TYPE,
                                         P_DESCRICAO IN P2P_ITEM.DESCRICAO%TYPE)IS
BEGIN
    INSERT INTO P2P_ITEM (ID_CATEGORIA, RARIDADE, NOME, DESCRICAO)
        VALUES (P_ID_CATEGORIA, P_RARIDADE, P_NOME, P_DESCRICAO);
END ADD_P2P_ITEM;
/

SELECT * FROM P2P_CATEGORIA;
BEGIN
    ADD_P2P_ITEM(2, 1, 'ESPADA DE PRATA', '+3 DMG, -1 DUR');
    ADD_P2P_ITEM(3, 2, 'PEITORAL DE OURO', '+5 DEF, -2 VEL');
    ADD_P2P_ITEM(3, 4, 'CALÇA DO ANJO', '+473 DEF, +79 DEX, + 20 INT, +50 VEL');
    ADD_P2P_ITEM(2, 1, 'GRAVETO', '+1DMG, -2 DUR');
    ADD_P2P_ITEM(4, 1, 'POÇÃO DE CURA PEQUENA', '+1 HP');
    ADD_P2P_ITEM(4, 3, 'POÇÃO DE STAMINA GRANDE', '+75 STM, 5 MIN');
    ADD_P2P_ITEM(4, 4, 'POÇÃO DA BRUXA DO BOSQUE', '-500HP, CEGUEIRA 2 MIN');
    ADD_P2P_ITEM(5, 2, 'COLAR DO GOBLIN', '+2 STM');
    ADD_P2P_ITEM(5, 1, 'BRINCO DE DENTE DE LOBO', 'ESTETICA');
    ADD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
END;
/
SELECT * FROM P2P_ITEM;

CREATE OR REPLACE PROCEDURE UPD_P2P_ITEM(P_NOME IN P2P_ITEM.NOME%TYPE,
                                         P_ID_CATEGORIA IN P2P_ITEM.ID_CATEGORIA%TYPE,
                                         P_NOVA_RARIDADE IN P2P_ITEM.RARIDADE%TYPE,
                                         P_NOVA_DESCRICAO IN P2P_ITEM.DESCRICAO%TYPE)IS
BEGIN
    UPDATE P2P_ITEM
        SET ID_CATEGORIA = P_ID_CATEGORIA,
            RARIDADE = P_NOVA_RARIDADE,
            DESCRICAO = P_NOVA_DESCRICAO
        WHERE NOME = P_NOME;
END UPD_P2P_ITEM;
/

BEGIN
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
    UPD_P2P_ITEM(5, 3, 'CHAPEU DE MASMORRA NVL16', '+10 HP, +20 DEF');
END;
/